env:
  browser: true
  es6: true
globals:
  "$": true
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
  "indent": ["error", 2],
  "no-dupe-args": "error",
  "no-dupe-keys": "error",
  "no-func-assign": "error",
  "no-redeclare": "error",
  "no-const-assign": "error",
  "no-return-assign": "error",
  "no-unexpected-multiline": "error",
  "no-unreachable": "error",
  "no-unused-expressions": "error",
  }
